server:
  port: 8083

logging:
  level:
    uk:
      gov:
        hmcts:
          fortifyclient: INFO

management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.sscs.controllers

idam:
  s2s-auth:
    url: ${IDAM_S2S_URL:http://localhost:4502}
    secret: ${IDAM_S2S_AUTH_TOTP_SECRET:AAAAAAAAAAAAAAAA}
    name: ${S2S_NAME_SSCS_HEARINGS_API:sscs-hearings-api}
    totp_secret: ${IDAM_S2S_AUTH_TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM_S2S_AUTH_MICROSERVICE:sscs}
  s2s-authorised:
    services: ${SSCS_S2S_AUTHORIZED_SERVICES:sscs,ccd,ccd_data,ccd_gw,ccd_ps}

spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import: "optional:configtree:/mnt/secrets/"
  application:
    name: SSCS Hearings API
  security:
    anonymousPaths:
      - "/"
      - "/health"
      - "/health/liveness"
      - "/health/readiness"
      - "/swagger-ui.html"
      - "/swagger-ui/index.html"
      - "/v3/api-docs/**"
      - "/favicon.ico"

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:false}

location_ref:
  api:
    url: ${LOCATION_REF_API_URL:http://localhost:8081}
