server:
  port: 8083

logging:
  level:
    uk.gov.hmcts.reform.sscs: ${SSCS_LOG_LEVEL:INFO}
    com.microsoft.azure.servicebus: ${SERVICE_BUS_LOG_LEVEL:ERROR}
    com.azure.messaging.servicebus: ${SERVICE_BUS_LOG_LEVEL:ERROR}
    com.azure.core.amqp: ${SERVICE_BUS_LOG_LEVEL:ERROR}

management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.sscs.controllers

spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import: "optional:configtree:/mnt/secrets/sscs/"
  application:
    name: SSCS Hearings API
  security:
    anonymousPaths:
      - "/"
      - "/health"
      - "/health/liveness"
      - "/health/readiness"
      - "/swagger-ui.html"
      - "/swagger-ui/index.html"
      - "/swagger-ui/swagger-ui-bundle.js"
      - "/swagger-ui/swagger-ui-standalone-preset.js"
      - "/swagger-ui/swagger-ui.css"
      - "/v3/api-docs/**"
      - "/favicon.ico"
  jackson:
    deserialization:
      read-unknown-enum-values-as-null: true
    serialization:
      write-dates-as-timestamps: false
    mapper:
      accept-case-insensitive-enums: true
      accept-case-insensitive-properties: true

feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
    retryer:
      period: 500
      maxPeriod: 2000
      maxAttempts: 3

azure:
  service-bus:
    amqp-connection-string-template : ${AMQP_CONNECTION_STRING:amqps://%1s?amqp.idleTimeout=%2d}
    connection-postfix: ${HMC_HEARINGS_TOPIC_CONNECTION_POSTFIX:.servicebus.windows.net}
    hmc-to-hearings-api:
      namespace: ${HMC_HEARINGS_TOPIC_NAMESPACE:}
      topicName: ${HMC_HEARINGS_TOPIC_NAME:}
      subscriptionName: ${HMC_HEARINGS_TOPIC_SUBSCRIPTION_NAME:}
      receiveTimeout: ${HMC_HEARINGS_TOPIC_RECEIVE_TIMEOUT:1}
      idleTimeout: ${HMC_HEARINGS_TOPIC_IDLE_TIMEOUT:3600000}
      username: ${HMC_HEARINGS_TOPIC_POLICY_NAME:}
      password: ${HMC_HEARINGS_TOPIC_ACCESS_KEY:}
    tribunals-to-hearings-api:
      namespace: ${TRIBUNALS_EVENT_QUEUE_NAMESPACE:}
      queueName: ${TRIBUNALS_EVENT_QUEUE_NAME:}
      receiveTimeout: ${TRIBUNALS_EVENT_QUEUE_RECEIVE_TIMEOUT:1}
      idleTimeout: ${TRIBUNALS_EVENT_QUEUE_IDLE_TIMEOUT:3600000}
      username: ${TRIBUNALS_EVENT_QUEUE_POLICY_NAME:}
      password: ${TRIBUNALS_EVENT_QUEUE_ACCESS_KEY:}
idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  s2s-auth:
    url: ${IDAM_S2S_URL:http://localhost:4502}
    name: ${S2S_NAME_SSCS_HEARINGS_API:sscs-hearings-api}
    totp_secret: ${IDAM_S2S_AUTH_TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: sscs
  s2s-authorised:
    services: ${IDAM_S2S_AUTH_MICROSERVICES:sscs,xui_webapp}
  client:
    id: ${IDAM_OAUTH2_CLIENT_ID:}
    secret: ${IDAM_OAUTH2_CLIENT_SECRET:}
  oauth2:
    user:
      email: ${IDAM_SSCS_SYSTEMUPDATE_USER:system.update@hmcts.net}
      password: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD:Pa55word11}

sscs:
  serviceCode: ${SSCS_SERVICE_CODE:BBA3}

caseworker-ref:
  api:
    url: ${CASEWORKER_REF_API_URL:http://localhost:8095}

common-ref:
  api:
    url: ${COMMON_REF_API_URL:http://localhost:4550}

core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}
  caseTypeId: ${CORE_CASE_DATA_CASE_TYPE_ID:Benefit}
  jurisdictionId: ${CORE_CASE_DATA_JURISDICTION_ID:SSCS}

judicial-ref:
  api:
    url: ${JUDICIAL_REF_API_URL:http://localhost:8093}

ccd-callback-orchestrator:
  api:
    url: ${CCD_CALLBACK_ORCHESTRATOR_API_URL:http://localhost:8070}

exui:
  url: ${EXUI_API_URL:http://localhost:3455}

hmc:
  url: ${HMC_API_URL:http://localhost:8084}
  deployment-id: ${HMC_DEPLOYMENT_ID:}

flags:
  hmc-to-hearings-api:
    enabled: ${HMC_HEARINGS_LISTENING_ENABLED:false}
  tribunals-to-hearings-api:
    enabled: ${TRIBUNALS_HEARINGS_LISTENING_ENABLED:true}
  adjournment:
    enabled: ${ADJOURNMENT_ENABLED:true}
  postHearings:
    enabled: ${POST_HEARING_ENABLED:true}
  deployment-filter:
    enabled: ${HMC_DEPLOYMENT_FILTER_ENABLED:false}

retry:
  hearing-response-update:
    max-retries: 3
    backoff: 3_000 #3 seconds

