server:
  port: 8083

logging:
  level:
    uk:
      gov:
        hmcts:
          fortifyclient: INFO

management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.sscs.controllers

spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import: "optional:configtree:/mnt/secrets/"
  application:
    name: SSCS Hearings API
  security:
    anonymousPaths:
      - "/"
      - "/health"
      - "/health/liveness"
      - "/health/readiness"
      - "/swagger-ui.html"
      - "/swagger-ui/index.html"
      - "/swagger-ui/swagger-ui-bundle.js"
      - "/swagger-ui/swagger-ui-standalone-preset.js"
      - "/swagger-ui/swagger-ui.css"
      - "/v3/api-docs/**"
      - "/favicon.ico"
      - "/serviceHearingValues"

jackson:
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:false}

feign:
  httpclient:
    enabled: true

core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}
  caseTypeId: ${CORE_CASE_DATA_CASE_TYPE_ID:Benefit}
  jurisdictionId: ${CORE_CASE_DATA_JURISDICTION_ID:SSCS}

sscs:
  serviceCode: ${SSCS_SERVICE_CODE:BBA3}

judicial-ref:
  api:
    url: ${JUDICIAL_REF_API_URL:http://localhost:8093}

exui:
  url: ${EXUI_API_URL:http://localhost:3455}

caseworker-ref:
  api:
    url: ${CASEWORKER_REF_API_URL:http://localhost:8095}

common-ref:
  api:
    url: ${COMMON_REF_API_URL:http://localhost:4550}

idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  s2s-auth:
    url: ${IDAM_S2S_URL:http://localhost:4502}
    secret: ${IDAM_S2S_AUTH_TOTP_SECRET:AAAAAAAAAAAAAAAA}
    name: ${S2S_NAME_SSCS_HEARINGS_API:sscs-hearings-api}
    totp_secret: ${IDAM_S2S_AUTH_TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM_S2S_AUTH_MICROSERVICE:sscs}
  s2s-authorised:
    services: ${SSCS_S2S_AUTHORIZED_SERVICES:sscs,ccd,ccd_data,ccd_gw,ccd_ps}
  oauth2:
    user:
      email: ${IDAM_SSCS_SYSTEMUPDATE_USER:system.update@hmcts.net}
      password: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD:Pa55word11}






