server:
  port: 8083

logging:
  level:
    uk:
      gov:
        hmcts:
          fortifyclient: INFO

management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.sscs.controllers

idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  s2s-auth:
    url: ${IDAM_S2S_URL:http://localhost:4502}
    secret: ${IDAM_S2S_AUTH_TOTP_SECRET:AAAAAAAAAAAAAAAA}
    name: ${S2S_NAME_SSCS_HEARINGS_API:sscs-hearings-api}
    totp_secret: ${IDAM_S2S_AUTH_TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM_S2S_AUTH_MICROSERVICE:sscs}
  s2s-authorised:
    services: ${SSCS_S2S_AUTHORIZED_SERVICES:sscs,ccd,ccd_data,ccd_gw,ccd_ps}
  oauth2:
    user:
      email: ${IDAM_SSCS_SYSTEMUPDATE_USER:system.update@hmcts.net}
      password: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD:Pa55word11}

spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import: "optional:configtree:/mnt/secrets/"
  application:
    name: SSCS Hearings API
  security:
    anonymousPaths:
      - "/"
      - "/health"
      - "/health/liveness"
      - "/health/readiness"
      - "/swagger-ui.html"
      - "/swagger-ui/index.html"
      - "/swagger-ui/swagger-ui-bundle.js"
      - "/swagger-ui/swagger-ui-standalone-preset.js"
      - "/swagger-ui/swagger-ui.css"
      - "/v3/api-docs/**"
      - "/favicon.ico"
      - "/serviceHearingValues"

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:false}
  service-bus:
    hmc-to-hearings-api:
      connectionString: ${HEARINGS_TOPIC_CONNECTION_STRING:}
      topicName: ${HEARINGS_TOPIC_NAME:}
      subscriptionName: ${HEARINGS_TOPIC_SUBSCRIPTION_NAME:}
      retryTimeout: ${HEARINGS_TOPIC_RETRY_TIMEOUT:1}
      maxRetries: ${HEARINGS_TOPIC_RETRIES:5}
      retryDelay: ${HEARINGS_TOPIC_RETRY_DELAY:1}

sscs:
  serviceCode: ${SSCS_SERVICE_CODE:BBA3}

feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
    retryer:
      period: 500
      maxPeriod: 2000
      maxAttempts: 3


caseworker-ref:
  api:
    url: ${CASEWORKER_REF_API_URL:http://localhost:8095}

common-ref:
  api:
    url: ${COMMON_REF_API_URL:http://localhost:4550}

core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}
  jurisdictionId: SSCS
  caseTypeId: Benefit

judicial-ref:
  api:
    url: ${JUDICIAL_REF_API_URL:http://localhost:8093}

exui:
  url: ${EXUI_API_URL:http://localhost:3455}

flags:
  hmc-to-hearings-api:
    enabled: ${HMC_HEARING_LISTENING_ENABLED:false}
